
// Types d'actions films 
export const GET_ALL_FILMS_PAGINATION = "GET_ALL_FILMS_PAGINATION";
export const GET_ALL_FILMS__PAGINATION_SUCCESS = "GET_ALL_FILMS__PAGINATION_SUCCESS";
export const GET_ALL_FILMS__PAGINATION_FAIL = "GET_ALL_FILMS__PAGINATION_FAIL";




export const GET_ALL_FILMS = "GET_ALL_FILMS";
export const GET_ALL_FILMS_SUCCESS = "GET_ALL_FILMS_SUCCESS";
export const GET_ALL_FILMS_FAIL = "GET_ALL_FILMS_FAIL";

export const GET_FILM_DETAIL = "GET_FILM_DETAIL";
export const GET_FILM_DETAIL_SUCCESS = "GET_FILM_DETAIL_SUCCESS";
export const GET_FILM_DETAIL_FAIL = "GET_FILM_DETAIL_FAIL";

export const ADD_FILM = "ADD_FILM";
export const ADD_FILM_SUCCESS = "ADD_FILM_SUCCESS";
export const ADD_FILM_FAIL = "ADD_FILM_FAIL";

export const DELETE_FILM = "DELETE_FILM";

export const UPDATE_FILM = "UPDATE_FILM";
// Types d'actions categorie

// src/redux/actions/types.js
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL';


export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

export const GET_FILMS_BY_CATEGORY = "GET_FILMS_BY_CATEGORY";
export const GET_FILMS_BY_CATEGORY_SUCCESS = "GET_FILMS_BY_CATEGORY_SUCCESS";
export const GET_FILMS_BY_CATEGORY_FAIL = "GET_FILMS_BY_CATEGORY_FAIL";

